spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://xxxxxxxxxxx/customer_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
